/**
 * gen_dresden_corrections.ts — Build script.
 *
 * Reads the Python ephemeris_corrections.py table (Swiss Ephemeris −
 * Meeus integer arcseconds) and emits src/lib/qmnf/dresden_corrections.generated.ts
 * as typed Int32Array blocks keyed by planet.
 *
 * Usage:  bun run scripts/gen_dresden_corrections.ts [path-to-python-file]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const PY_DEFAULT = "/tmp/kimi_astro/ephemeris_corrections.py";
const OUT_PATH = resolve(import.meta.dirname, "../src/lib/qmnf/dresden_corrections.generated.ts");

function parsePythonAssignNumber(src: string, name: string): number {
  const re = new RegExp(`${name}\\s*=\\s*(-?\\d+)`);
  const m = src.match(re);
  if (!m) throw new Error(`Couldn't find ${name} assignment`);
  return Number(m[1]);
}

function parsePythonArrayList(src: string, planet: string): number[] {
  // Match  'Planet': [ ... ]  (greedy across newlines, until closing ])
  const re = new RegExp(`'${planet}'\\s*:\\s*\\[([\\s\\S]*?)\\]`, "m");
  const m = src.match(re);
  if (!m) throw new Error(`Couldn't find ${planet} array`);
  return m[1]
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map((s) => {
      const n = Number(s);
      if (!Number.isFinite(n)) throw new Error(`Bad value in ${planet}: ${s}`);
      return n;
    });
}

function main() {
  const pyPath = process.argv[2] ?? PY_DEFAULT;
  const src = readFileSync(pyPath, "utf8");

  const CORR_START = parsePythonAssignNumber(src, "CORR_START");
  const CORR_STEP_DEFAULT = parsePythonAssignNumber(src, "CORR_STEP_DEFAULT");
  const CORR_STEP_MARS = parsePythonAssignNumber(src, "CORR_STEP_MARS");
  let CORR_STEP_VENUS = CORR_STEP_DEFAULT;
  try {
    CORR_STEP_VENUS = parsePythonAssignNumber(src, "CORR_STEP_VENUS");
  } catch {
    /* optional */
  }

  const planets = ["Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"];
  const tables: Record<string, { step: number; data: number[] }> = {};
  for (const p of planets) {
    let arr: number[];
    try {
      arr = parsePythonArrayList(src, p);
    } catch {
      console.warn(`skip ${p} (no data)`);
      continue;
    }
    const step =
      p === "Mars" ? CORR_STEP_MARS : p === "Venus" ? CORR_STEP_VENUS : CORR_STEP_DEFAULT;
    tables[p] = { step, data: arr };
  }

  // Maya-day START → JD start.  JD = maya_day + 584283.
  const JD_START = CORR_START + 584283;

  let out = `// AUTO-GENERATED by scripts/gen_dresden_corrections.ts — do not edit by hand.
// Source: ${pyPath.replace(/^.*\//, "")}
// Each value is an integer arcsecond correction (Swiss Ephemeris − Meeus VSOP).
// Tables are interpolated at runtime via pure-integer arithmetic.

export const DRESDEN_CORR_JD_START = ${JD_START};
export const DRESDEN_CORR_MAYA_START = ${CORR_START};
export const DRESDEN_CORR_STEP_DEFAULT = ${CORR_STEP_DEFAULT};
export const DRESDEN_CORR_STEP_MARS = ${CORR_STEP_MARS};
export const DRESDEN_CORR_STEP_VENUS = ${CORR_STEP_VENUS};

export interface DresdenCorrectionTable {
  step: number;       // days between samples
  data: Int32Array;   // arcsec corrections (integer)
}

export const DRESDEN_CORRECTIONS: Record<string, DresdenCorrectionTable> = {
`;
  for (const [name, t] of Object.entries(tables)) {
    // Encode as a comma list inside Int32Array(...) — keeps the bundle compact.
    out += `  ${name}: { step: ${t.step}, data: new Int32Array([${t.data.join(",")}]) },\n`;
  }
  out += `};\n`;
  out += `\nexport const DRESDEN_CORR_PLANETS: ReadonlyArray<string> = ${JSON.stringify(Object.keys(tables))};\n`;
  writeFileSync(OUT_PATH, out, "utf8");

  const total = Object.values(tables).reduce((s, t) => s + t.data.length, 0);
  console.log(`Wrote ${OUT_PATH}`);
  console.log(`  Planets: ${Object.keys(tables).join(", ")}`);
  console.log(`  Total samples: ${total}`);
  console.log(`  JD_START = ${JD_START}  (maya_day ${CORR_START})`);
}

main();
